name: Tuono App Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust (for safety)
        run: rustup update stable

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install tuono CLI
        run: cargo install tuono

      - name: Install JS dependencies
        run: npm install
        
      - name: Build production assets
        run: tuono build

      - name: Run production server
        run: cargo run --release
