name: Tuono Static Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-static:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust (for safety)
        run: rustup update stable

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Tuono CLI
        run: cargo install tuono-cli

      - name: Install npm dependencies
        run: npm install

      - name: Build static site
        run: tuono build

      - name: Upload static site artifact
        uses: actions/upload-artifact@v4
        with:
          name: tuono-static-site
          path: out/
